"""
언론사 도메인 매핑 관리 파일
"""

PRESS_MAP = {
    # 뉴스통신 / 종합
    "yna.co.kr": "연합뉴스",
    "yonhapnews.co.kr": "연합뉴스",
    "newsis.com": "뉴시스",
    "news1.kr": "뉴스1",
    "nocutnews.co.kr": "노컷뉴스",
    "ohmynews.com": "오마이뉴스",
    "pressian.com": "프레시안",

    # 종합 일간지
    "chosun.com": "조선일보",
    "joongang.co.kr": "중앙일보",
    "donga.com": "동아일보",
    "hani.co.kr": "한겨레",
    "khan.co.kr": "경향신문",
    "hankookilbo.com": "한국일보",
    "seoul.co.kr": "서울신문",
    "segye.com": "세계일보",
    "munhwa.com": "문화일보",
    "kmib.co.kr": "국민일보",

    # 방송사
    "kbs.co.kr": "KBS",
    "mbc.co.kr": "MBC",
    "sbs.co.kr": "SBS",
    "jtbc.co.kr": "JTBC",
    "tvchosun.com": "TV조선",
    "mbn.co.kr": "MBN",
    "ytn.co.kr": "YTN",
    "yonhapnewstv.co.kr": "연합뉴스TV",

    # 경제지
    "mk.co.kr": "매일경제",
    "hankyung.com": "한국경제",
    "sedaily.com": "서울경제",
    "fnnews.com": "파이낸셜뉴스",
    "edaily.co.kr": "이데일리",
    "mt.co.kr": "머니투데이",
    "asiae.co.kr": "아시아경제",
    "heraldcorp.com": "헤럴드경제",
    "biz.chosun.com": "조선비즈",
    "bizwatch.co.kr": "비즈워치",
    "thebell.co.kr": "더벨",
    "dealsite.co.kr": "딜사이트",
    "businesspost.co.kr": "비즈니스포스트",
    "etoday.co.kr": "이투데이",
    "newspim.com": "뉴스핌",
    "moneys.co.kr": "머니S",

    # IT / 테크
    "etnews.com": "전자신문",
    "zdnet.co.kr": "지디넷코리아",
    "bloter.net": "블로터",
    "itworld.co.kr": "ITWorld",
    "ciokorea.com": "CIO Korea",
    "ddaily.co.kr": "디지털데일리",
    "dt.co.kr": "디지털타임스",
    "inews24.com": "아이뉴스24",
    "aitimes.com": "AI타임스",
    "aitimes.kr": "AI타임스",
    "byline.network": "바이라인네트워크",
    "venturesquare.net": "벤처스퀘어",
    "platum.kr": "플래텀",
    "techm.kr": "테크M",
    "digitaltoday.co.kr": "디지털투데이",
    "boannews.com": "보안뉴스",
    "dailysecu.com": "데일리시큐",
    "hellodd.com": "헬로디디",
    "sciencetimes.co.kr": "사이언스타임즈",
    "dongascience.com": "동아사이언스",
    "koit.co.kr": "정보통신신문",
    "thelec.kr": "디일렉",

    # 의료 / 헬스케어 / 바이오
    "medicaltimes.com": "메디컬타임즈",
    "medipana.com": "메디파나뉴스",
    "doctorsnews.co.kr": "의협신문",
    "monews.co.kr": "메디칼업저버",
    "docdocdoc.co.kr": "청년의사",
    "hitnews.co.kr": "히트뉴스",
    "dailymedi.com": "데일리메디",
    "bosa.co.kr": "의학신문",
    "yakup.com": "약업신문",
    "pharmnews.com": "팜뉴스",
    "pharmnews.co.kr": "팜뉴스",
    "pharmstoday.com": "메디팜스투데이",
    "mdtoday.co.kr": "메디컬투데이",
    "healthinnews.co.kr": "헬스인뉴스",
    "health.chosun.com": "헬스조선",
    "k-health.com": "헬스경향",
    "biospectator.com": "바이오스펙테이터",
    "medigatenews.com": "메디게이트뉴스",
    "whosaeng.com": "후생신보",
    "rapportian.com": "라포르시안",
    "healtho.co.kr": "헬스오",
    "newsmp.com": "의약뉴스",
    "medicalworldnews.co.kr": "메디컬월드뉴스",
    "kmedinfo.co.kr": "한국의약통신",
    "medical-tribune.co.kr": "메디칼트리뷴",
    "clinicjournal.co.kr": "클리닉저널",
    "doctorstimes.com": "의사신문",

    # 지역지
    "kihoilbo.co.kr": "기호일보",
    "kyeonggi.com": "경기일보",
    "kgnews.co.kr": "경기신문",
    "kyeongin.com": "경인일보",
    "joongboo.com": "중부일보",
    "incheonilbo.com": "인천일보",
    "kado.net": "강원도민일보",
    "kwnews.co.kr": "강원일보",
    "knnews.co.kr": "경남신문",
    "idomin.com": "경남도민일보",
    "hidomin.com": "경북도민일보",
    "kyongbuk.co.kr": "경북일보",
    "imaeil.com": "매일신문",
    "idaegu.com": "대구일보",
    "busan.com": "부산일보",
    "kookje.co.kr": "국제신문",
    "kwangju.co.kr": "광주일보",
    "jnilbo.com": "전남일보",
    "jjan.kr": "전북일보",
    "domin.co.kr": "전북도민일보",
    "jejunews.com": "제주일보",
    "ihalla.com": "한라일보",
    "cctoday.co.kr": "충청투데이",
    "ccdailynews.com": "충청일보",
    "daejonilbo.com": "대전일보",

    # 교육
    "veritas-a.com": "베리타스알파",
    "edupress.kr": "에듀프레스",
    "dhnews.co.kr": "대학저널",
    "kyosu.net": "교수신문",
    "news.unn.net": "한국대학신문",
    "hangyo.com": "한국교육신문",

    # 부동산 / 건설 / 산업
    "realty.chosun.com": "땅집고",
    "rcast.co.kr": "리얼캐스트",
    "hapt.co.kr": "한국아파트신문",
    "ikld.kr": "국토일보",
    "constimes.co.kr": "건설타임즈",
    "cnews.co.kr": "대한경제",
    "dnews.co.kr": "대한경제",
    "e2news.com": "이투뉴스",
    "electricpower.co.kr": "전기신문",
    "electimes.com": "전기신문",
    "industrynews.co.kr": "인더스트리뉴스",

    # 시사 / 미디어
    "sisain.co.kr": "시사IN",
    "sisajournal.com": "시사저널",
    "mediatoday.co.kr": "미디어오늘",
    "mediaus.co.kr": "미디어스",
    "journalist.or.kr": "기자협회보",
    "pdjournal.com": "PD저널",
    "newstof.com": "뉴스톱",

    # 스포츠 / 연예 / 문화
    "sportsseoul.com": "스포츠서울",
    "sportschosun.com": "스포츠조선",
    "spotvnews.co.kr": "스포티비뉴스",
    "osen.co.kr": "OSEN",
    "xportsnews.com": "엑스포츠뉴스",
    "starnews.co.kr": "스타뉴스",
    "newsen.com": "뉴스엔",
    "dispatch.co.kr": "디스패치",
    "cine21.com": "씨네21",
    "tenasia.hankyung.com": "텐아시아",

    # 영자지 / 외신
    "koreaherald.com": "코리아헤럴드",
    "koreatimes.co.kr": "코리아타임스",
    "koreajoongangdaily.joins.com": "코리아중앙데일리",
    "arirang.com": "아리랑TV",
    "reuters.com": "로이터",
    "bloomberg.com": "블룸버그",
    "apnews.com": "AP뉴스",
    "cnn.com": "CNN",
    "bbc.com": "BBC",
    "nytimes.com": "뉴욕타임스",
    "wsj.com": "월스트리트저널",
    "ft.com": "파이낸셜타임스",

    # 추가
    "kdpress.co.kr": "데일리경제",
    "bokuennews.com": "보건뉴스",
    "inews365.com": "충북일보",
    "shinailbo.co.kr": "신아일보",
    "dailian.co.kr": "데일리안",
    "job-post.co.kr": "잡포스트",
        "the-stock.kr": "더스탁",
    "pinpointnews.co.kr": "핀포인트뉴스",
    "getnews.co.kr": "글로벌경제신문",
    "pressman.kr": "프레스맨",
    "cstimes.com": "컨슈머타임스",
    "m-economynews.com": "M이코노미뉴스",
    "news.bbsi.co.kr": "BBS뉴스",
    "bbsi.co.kr": "BBS뉴스",
    "koreastocknews.com": "한국증권신문",
    "popcornnews.net": "팝콘뉴스",
    "daily.hankooki.com": "데일리한국",
    "seoulfn.com": "서울파이낸스",
    "news.tf.co.kr": "더팩트",
    "tf.co.kr": "더팩트",
    "koreahealthlog.com": "코리아헬스로그",
    "viva100.com": "브릿지경제",

    "cbci.co.kr": "CBC뉴스",
    "thefirstmedia.net": "더퍼스트미디어",
    "womaneconomy.co.kr": "여성경제신문",
    "newsbrite.net": "뉴스브라이트",
    "ebn.co.kr": "EBN",
    "weekly.hankooki.com": "주간한국",
    "newsworks.co.kr": "뉴스웍스",
    "mediapen.com": "미디어펜",
    "it-b.co.kr": "아이티비즈",
    "sentv.co.kr": "서울경제TV",
    "newslock.co.kr": "뉴스락",
    "newsway.co.kr": "뉴스웨이",

}